language: "node_js"
install:
- if [ "$CXX" = "g++" ]; then export CXX="g++-4.8" CC="gcc-4.8"; fi
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-4.8
    - g++-4.8
node_js:
  - '0.10'
  - '0.12'
  - '4.1'
  - 'iojs'
script: npm install&&node test/test.js
